# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [3]:
%tensorflow_version

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [30]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

2.1.0


### Set random seed

In [6]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
# Import pandas 
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Read in white wine data 
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [31]:
feature_set = iris.data
target_set = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [20]:
from sklearn.model_selection import train_test_split
# Split the data up in train and test sets
X_train, X_test, y_train, y_test = train_test_split(feature_set, target_set, test_size=0.25, random_state=600)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [77]:
y_train_binary = keras.utils.to_categorical(y_train, num_classes=None)
y_train_binary

y_test_binary = keras.utils.to_categorical(y_test, num_classes=None)
y_test_binary

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [35]:
# Initialize the constructor
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [37]:
# Add an input layer 
model.add(tf.keras.layers.Dense(10, input_shape=(4,)))

# Add an output layer 
model.add(tf.keras.layers.Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [70]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
print(model)
print(model.optimizer)
print(model.loss)
print(model.metrics_names)

categorical_crossentropy
['loss', 'accuracy']


## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [62]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [75]:
history = model.fit(X_train, y_train_binary,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.1662 - accuracy: 0.9196
Epoch 2/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.1976 - accuracy: 0.9286
Epoch 3/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.1504 - accuracy: 0.9375
Epoch 4/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.1806 - accuracy: 0.9107
Epoch 5/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.1887 - accuracy: 0.9196
Epoch 6/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1493 - accuracy: 0.93750s - loss: 0.1282 - accuracy: 
Epoch 7/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1292 - accuracy: 0.9554
Epoch 8/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.1551 - accuracy: 0.9196
Epoch 9/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1443 - accuracy: 0.9464
Epoch 10/100
112/112 [

In [78]:
score = model.evaluate(X_test, y_test_binary,verbose=1)

print(score)

38/38 [==============================] - 0s 4ms/sample - loss: 0.0254 - accuracy: 1.0000
[0.02539921592381832, 1.0]


## Question 10

### Make predictions
- Predict labels on one row

In [85]:
pred = np.round(model.predict(X_test))
pred[0]

array([1., 0., 0.], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [86]:
y_test_binary[0]

array([1., 0., 0.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [87]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [2]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [5]:
prices = pd.read_csv("data/prices.csv")

In [6]:
prices.head(2)

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   

      volume  
0  2163600.0  
1  2386400.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [7]:
prices.drop(['date','symbol'],axis =1,inplace=True)

In [8]:
prices.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [9]:
prices = prices.head(1000)
prices.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [10]:
feature_set = prices.drop('volume',axis=1)
target_set = prices[['volume']].copy()
target_set.columns = ['volume']
target_set = target_set / 1000000

target_set.head()

volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [17]:
feature_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float64
close    1000 non-null float64
low      1000 non-null float64
high     1000 non-null float64
dtypes: float64(4)
memory usage: 31.3 KB


In [18]:
target_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
volume    1000 non-null float64
dtypes: float64(1)
memory usage: 7.9 KB


In [19]:
feature_set_arr = feature_set.values
target_set_arr = target_set.values

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [38]:
feature_l2nor= tf.math.l2_normalize(feature_set_arr.astype('float32'))
feature_l2nor

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [45]:
weight = tf.Variable(tf.zeros([4,1]))
bias = tf.Variable(tf.zeros([1]))

weight

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [46]:
def prediction(x_train,w, b):
    p = tf.matmul(x_train,w) + b
    return p
    
    
pred = prediction(feature_l2nor,weight, bias)
#print(pred)

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [70]:
def loss(error):
    # print('inside error func ')
    loss = tf.reduce_mean(tf.square(error))
    # print(loss)
    return loss;

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [73]:
#training info
train_steps = 100
learning_rate = 0.01

for i in range(train_steps):
    #watch the gradient flow 
    with tf.GradientTape() as tape:
        #forward pass 
        yhat = prediction(feature_l2nor,weight,bias)            
        #calcuate the loss (difference squared error)
        error = tf.math.subtract(yhat,tf.convert_to_tensor(target_set_arr, dtype=tf.float32))
        l = loss(error)

    #dw dbias 
    dw, db = tape.gradient(l, [weight, bias])

    #update the weights and biases 
    weight.assign_sub(dw * learning_rate)
    bias.assign_sub(db* learning_rate)
    
    #print the loss every 10 iterations 
    if i % 10 == 0:
        print("Loss at step {:03d}: {:.3f}".format(i, l))
      
print(f'W : {weight.numpy()} , b  = {bias.numpy()} ')

Loss at step 000: 209.051
Loss at step 010: 209.048
Loss at step 020: 209.046
Loss at step 030: 209.045
Loss at step 040: 209.044
Loss at step 050: 209.043
Loss at step 060: 209.042
Loss at step 070: 209.041
Loss at step 080: 209.041
Loss at step 090: 209.040
W : [[-0.04549415]
 [-0.04487491]
 [-0.04461769]
 [-0.04553549]] , b  = [5.304813] 


## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
## please look in the above cell

### Observe values of Weight
- Print the updated values

In [74]:
weight.numpy()

array([[-0.04549415],
       [-0.04487491],
       [-0.04461769],
       [-0.04553549]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [75]:
bias.numpy()

array([5.304813], dtype=float32)